version: '3' #Docker version
services:
  www: 
    # image: php:apache
    build:
      context: .
      dockerfile: client.Dockerfile # my Dockerfile in frontend
    volumes:
      -  "./:/var/www/html" #sync project dir with container web dir
    ports:
      - 8081:80
  db:
    image: mysql:latest
    environment:
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
    - "./db:/docker-entrypoint-initdb.d" # sync persistent sql files with container
  phpmyadmin:
    image: phpmyadmin
    ports: 
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3307
